name: harmony
description: >
  Just a Bot.
version: 0.1.0
authors:
  - Matan Lurey <matan@lurey.org>
homepage: https://github.com/matanlurey/harmony-bot

environment:
  sdk: ">=1.22.0 <2.0.0"

dependencies:
  args: ^1.0.0
  cable:
  cable_stackdriver:
  din:
  io:
  stack_trace:
  timeago: ^1.0.0

dev_dependencies:
  mockito: ^2.0.0
  test: ^0.12.0
