name: harmony
description: >
  Just a Bot.
version: 0.1.0-dev+1
authors:
  - Matan Lurey <matan@lurey.org>
homepage: https://github.com/matanlurey/harmony

environment:
  sdk: ">=1.22.0 <2.0.0"

dependencies:
  args: ^1.0.0
  cable: ^0.1.0
  cable_stackdriver: ^0.1.1
  din: 0.1.0-alpha+8
  io:
    git:
      url: https://github.com/dart-lang/io.git
      ref: master
  stack_trace: ^1.9.1
  stack_trace_codec: ^0.1.0
  timeago: ^1.0.0

dev_dependencies:
  mockito: ^2.0.0
  test: ^0.12.0

# REMOVE BEFORE PUBLISHING.
dependency_overrides:
  din:
    git:
      url: https://github.com/matanlurey/din.git
      ref: more-feat
